// src/lib/pages/playground/ui/playground.svelte
<script lang="ts">
	import { Pane, PaneGroup, PaneResizer } from 'paneforge';
	import LucideMenu from '~icons/lucide/menu';
	import LucideSave from '~icons/lucide/save';
	import * as m from '$i18n/messages';
	import { Button } from '$lib/shared/ui/actions/button';

	let playgroundName = $state('Hello World');
</script>

<div
	class="capitalize-first flex min-h-0 flex-col pt-4 supports-[height:100dvh]:h-[calc(100dvh-var(--spacing-nav-height))]"
>
	<div class="bg-base-100 flex min-h-0 grow flex-col space-y-4 pt-4">
		<div class="flex gap-x-2 px-4">
			<Button title={m.known_bad_tadpole_relish()} iconOnly>
				{#snippet icon()}
					<LucideMenu />
				{/snippet}
			</Button>
			<input
				type="text"
				class="input input-bordered w-full"
				placeholder={m.misty_early_swan_enjoy({
					name: m.quiet_polite_yak_delight({ name: m.spicy_noble_boar_boost() })
				})}
				bind:value={playgroundName}
			/>
			<Button title={m.only_wild_wombat_jump({ name: playgroundName })} iconOnly>
				{#snippet icon()}
					<LucideSave />
				{/snippet}
			</Button>
		</div>
		<div class="border-base-content/20 h-full border-t">
			<PaneGroup direction="horizontal" class="">
				<Pane defaultSize={50}>Code section</Pane>
				<PaneResizer class="bg-base-content/20 w-0.5" />
				<Pane defaultSize={50} class="p-4">Result section</Pane>
			</PaneGroup>
		</div>
	</div>
</div>

// pages/playground/ui/playground.vue
<script setup lang="ts">
import { SplitterGroup, SplitterPanel, SplitterResizeHandle } from 'reka-ui'
import { Button } from '~/shared/ui/actions/button'
import { Input } from '~/shared/ui/data-input/input'
import LucideMenu from '~icons/lucide/menu'
import { OutputType } from '../configs/constants'
import Editor from './editor.vue'
import OutputResult from './output-result.vue'
import OutputAst from './output-ast.vue'
import OutputTablist from './output-tablist.vue'

const playgroundName = ref<string>('Hello world')

const activeOutput = ref(OutputType.Result)
</script>

<template>
	<div
		class="capitalize-first flex min-h-0 flex-col pt-4 supports-[height:100dvh]:h-[calc(100dvh-var(--spacing-nav-height))]"
	>
		<div class="bg-base-100 flex min-h-0 grow flex-col space-y-4 pt-4">
			<div class="flex gap-x-2 px-4">
				<Button title="Example" icon-only :icon="LucideMenu" />
				<Input
					v-model="playgroundName"
					placeholder="Please submit playground name"
					type="text"
					class="w-full"
				/>
			</div>
			<div class="border-base-content/20 h-full min-h-0 border-t">
				<SplitterGroup direction="horizontal">
					<SplitterPanel>
						<Editor />
					</SplitterPanel>

					<SplitterResizeHandle class="bg-base-content/20 w-0.5" />

					<SplitterPanel>
						<OutputTablist v-model:active-output="activeOutput" />

						<div :class="{ hidden: activeOutput !== OutputType.Result }">
							<OutputResult />
						</div>
						<div :class="{ hidden: activeOutput !== OutputType.Ast }">
							<OutputAst />
						</div>
					</SplitterPanel>
				</SplitterGroup>
			</div>
		</div>
	</div>
</template>
