// app/layouts/default/nav-item.vue
<script setup lang="ts">
import type { RouteLocationRaw } from 'vue-router'

const props = defineProps<{
	/** The URL the navigation item links to
	 *
	 * @requires
	 */
	to: RouteLocationRaw
	title: string
}>()
</script>

<template>
	<RouterLink :to="props.to" class="link hover:text-primary no-underline">
		{{ props.title }}
	</RouterLink>
</template>

// src/lib/shared/ui/page-layout/default/ui/nav-item.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';

	interface Props {
		/** The URL the navigation item links to
		 *
		 * @requires
		 */
		href: string;
		children?: Snippet;
	}

	let { href, children }: Props = $props();
</script>

<a {href} class="link hover:text-primary no-underline">
	{@render children?.()}
</a>
