// shared/ui/actions/button/button.vue
<script setup lang="ts">
import { computed, useSlots } from 'vue'
import type { ButtonProps } from './types'
import { buttonClassNameHandler } from './styles'
import { cn } from '~/shared/lib/utils/classname'

const props = defineProps<ButtonProps>()

const slots = useSlots()

const buttonClasses = computed(() => {
	if (props.unstyled) {
		return cn(props.class)
	}

	const buttonClasses = buttonClassNameHandler({
		color: props.color,
		variant: props.variant,
		icon: props.iconOnly,
		disabled: props.disabled || props.loading
	})

	return cn(buttonClasses, props.class)
})
</script>

<template>
	<button
		:class="buttonClasses"
		:disabled="props.disabled || props.loading"
		:title="props.title"
		:aria-label="props.title"
	>
		<span v-if="props.loading" class="loading loading-spinner loading-xs" />
		<component :is="props.icon" v-else />
		<span v-if="slots.default"><slot /></span>
		<component :is="props.altIcon" />
		<slot name="suffix" />
	</button>
</template>

// src/lib/shared/ui/actions/button/button.svelte
<script lang="ts">
	import { parseTextCapitalizeFirst } from '$lib/shared/lib/parser/text-capitalize-first';
	import { cn } from '$lib/shared/lib/utils/cn';
	import { buttonClassNameHandler } from './styles';
	import type { ButtonProps } from './types';

	const {
		tag = 'button',
		color,
		variant,
		class: className,
		iconOnly,
		unstyled,
		icon,
		altIcon,
		children,
		text,
		title,
		...props
	}: ButtonProps = $props();

	const buttonClasses = $derived.by(() => {
		// If the button is unstyled, return only the class name
		if (unstyled) {
			return cn(className);
		}

		return cn(
			buttonClassNameHandler({
				color,
				variant,
				icon: iconOnly
			}),
			className
		);
	});

	const formatedTitle = $derived.by(() => {
		return parseTextCapitalizeFirst(title);
	});
</script>

<svelte:element
	this={tag}
	class={buttonClasses}
	disabled={props.disabled || props.loading}
	title={formatedTitle}
	aria-label={formatedTitle}
>
	{#if props.loading}
		<span class="loading loading-spinner loading-sm"></span>
	{:else}
		{@render icon?.()}
	{/if}
	{#if text}
		<span>
			{text}
		</span>
	{:else if children}
		{@render children?.()}
	{/if}
	{#if altIcon}
		{@render altIcon?.()}
	{/if}
</svelte:element>
